import pygame

pygame.init()

GAME_TICK = pygame.USEREVENT + 1  # 25
TICKS_PER_SEC = 20
ONE_SEC = TICKS_PER_SEC
TEN_SEC = 10*TICKS_PER_SEC

DISPLAY_WIDTH = 1200
DISPLAY_HEIGHT = 700

MAP_SIZE = 9

TILE_WIDTH = 50
TILE_HEIGHT = 50

PERK_WIDTH = 100
PERK_HEIGHT = 50
PERK_OFFSET = 50
PERK_DIST = 25

GAME_OFFSETS = {'x': 50, 'y': 50}
GAME_OFFSET = (GAME_OFFSETS['x'], GAME_OFFSETS['y'])

GAME_WIDTH = 600
GAME_HEIGHT = 600

CHART_WIDTH = 240
CHART_HEIGHT = 240

BLACK = pygame.Color('black')
WHITE = pygame.Color('white')
RED = pygame.Color('red')
LIGHTGREEN = pygame.Color('lightgreen')
DARKGREEN = pygame.Color('darkgreen')
GREEN = pygame.Color('green')
GREY = pygame.Color('grey')
BLUE = pygame.Color('blue')
LIGHTBLUE = pygame.Color('lightblue')
YELLOW = pygame.Color('yellow')
PURPLE = pygame.Color('purple')
CYAN = pygame.Color('cyan')

WATER = (82, 146, 255)
GRASS = (95, 131, 33)
ROCK = (215, 255, 158)
SAND = (255, 235, 115)
ICE = (219, 243, 255)

# Coin cost of maps at different radii
MAP_COSTS = {0: 0,
             1: 100,
             2: 200,
             3: 400,
             4: 800}

TILE_INFO = {
             'r': {'name': 'Stone',
                   'color': GREY,
                   'can_spawn': {'rock': 10,
                                 'boulder': 5,
                                 'irondeposit': 2,
                                 'golddeposit': 2}},
             'w': {'name': 'Water',
                   'color': WATER,
                   'can_spawn': {'fish': 1}},
             'g': {'name': 'Grass',
                   'color': GRASS,
                   'can_spawn': {'tree': 1,
                                 'bush': 1}},
             's': {'name': 'Sand',
                   'color': SAND,
                   'can_spawn': {'sand': 10,
                                 'treasure': 1}},
             'i': {'name': 'Ice',
                   'color': ICE,
                   'can_spawn': {'none': 15,
                                 'loosegem': 1}}
             }

RESOURCES = {
             'rock': {'image_str': 'images/rocks.png',
                      'minetime': 5*ONE_SEC,
                      'minegives': {'stone': 1},
                      'minecosts': {'energy': 5}},
             'boulder': {'image_str': 'images/boulder.png',
                         'minetime': TEN_SEC,
                         'minegives': {'stone': 4},
                         'minecosts': {'energy': 20}},
             'irondeposit': {'image_str': 'images/iron.png',
                             'minetime': TEN_SEC,
                             'minegives': {'ironore': 2},
                             'minecosts': {'energy': 20}},
             'golddeposit': {'image_str': 'images/gold.png',
                             'minetime': TEN_SEC,
                             'minegives': {'goldore': 2},
                             'minecosts': {'energy': 20}},
             'fish': {'image_str': 'images/fish.png',
                      'minetime': 5*ONE_SEC,
                      'minegives': {'food': 1},
                      'minecosts': {'energy': 5}},
             'tree': {'image_str': 'images/tree.png',
                      'minetime': 5*ONE_SEC,
                      'minegives': {'wood': 2},
                      'minecosts': {'energy': 5}},
             'bush': {'image_str': 'images/bush.png',
                      'minetime': 5*ONE_SEC,
                      'minegives': {'food': 1},
                      'minecosts': {'energy': 5}},
             'sand': {'image_str': 'images/sand.png',
                      'minetime': ONE_SEC,
                      'minegives': {'sand': 1},
                      'minecosts': {'energy': 5}},
             'treasure': {'image_str': 'images/chest.png',
                          'minetime': ONE_SEC,
                          'minegives': {'coins': 20},
                          'minecosts': {'energy': 5}},
             'loosegem': {'image_str': 'images/gem.png',
                          'minetime': ONE_SEC,
                          'minegives': {'gem': 1},
                          'minecosts': {'energy': 5}},
             'animal trap': {'image_str': 'images/trap.png',
                             'minetime': ONE_SEC,
                             'minegives': {'food': 4},
                             'minecosts': {'energy': 5}},
             'house': {'image_str': 'images/house0.png',
                       'minetime': TEN_SEC,
                       'minegives': {'stone': 10,
                                     'wood': 20},
                       'minecosts': {'energy': 20},
                       'beds': 4,
                       'recruitcost': 20,
                       'confirmdestroy': True,
                       'upkeep': {'food': 1},
                       'frequency': TEN_SEC},
             'farm': {'image_str': 'images/farm.png',
                      'minetime': TEN_SEC,
                      'minegives': {'stone': 10,
                                    'wood': 20},
                      'minecosts': {'energy': 20},
                      'confirmdestroy': True,
                      'produces': {'food': 1},
                      'upkeep': {'workers': 1},
                      'frequency': TEN_SEC},
             'fishing shack': {'image_str': 'images/tackle.png',
                               'minetime': 5*ONE_SEC,
                               'minegives': {'stick': 5,
                                             'wood': 10},
                               'minecosts': {'energy': 20},
                               'confirmdestroy': True,
                               'gathers': ['fish'],
                               'workradius': 2,
                               'upkeep': {'workers': 1},
                               'frequency': 5*ONE_SEC},
             'forager hut': {'image_str': 'images/forager.png',
                             'minetime': 5*ONE_SEC,
                             'minegives': {'stick': 5,
                                           'wood': 10},
                             'minecosts': {'energy': 20},
                             'confirmdestroy': True,
                             'gathers': ['bush', 'rock', 'loosegem', 'sand'],
                             'workradius': 3,
                             'upkeep': {'workers': 1},
                             'frequency': 5*ONE_SEC},
             'lumberjack hut': {'image_str': 'images/choppingblock.png',
                                'minetime': 5*ONE_SEC,
                                'minegives': {'stone': 10,
                                              'wood': 20},
                                'minecosts': {'energy': 20},
                                'confirmdestroy': True,
                                'gathers': ['tree'],
                                'workradius': 3,
                                'upkeep': {'workers': 1},
                                'frequency': 5*ONE_SEC},
             'tree farm': {'image_str': 'images/treefarm.png',
                           'minetime': TEN_SEC,
                           'minegives': {'stone': 10,
                                         'wood': 20,
                                         'glass': 20},
                           'minecosts': {'energy': 20},
                           'confirmdestroy': True,
                           'produces': {'wood': 1},
                           'upkeep': {'workers': 1},
                           'frequency': TEN_SEC},
             'prospector': {'image_str': 'images/miner.png',
                            'minetime': 5*ONE_SEC,
                            'minegives': {'iron': 5,
                                          'stone': 10,
                                          'wood': 10},
                            'minecosts': {'energy': 20},
                            'confirmdestroy': True,
                            'gathers': ['boulder', 'irondeposit', 'golddeposit'],
                            'workradius': 2,
                            'upkeep': {'workers': 1},
                            'frequency': 5*ONE_SEC},
             'wood generator': {'symbol': "WG",
                                'minetime': 5*ONE_SEC,
                                'minegives': {'iron': 5,
                                              'stone': 10,
                                              'wood': 10},
                                'minecosts': {'energy': 20},
                                'confirmdestroy': True,
                                'powerproduced': 2,
                                'upkeep': {'wood': 1},
                                'frequency': 5*ONE_SEC},
             'iron mine': {'image_str': 'images/ironmine.png',
                           'minetime': TEN_SEC,
                           'minegives': {'stone': 20,
                                         'wood': 40,
                                         'iron': 10},
                           'minecosts': {'energy': 20},
                           'confirmdestroy': True,
                           'produces': {'ironore': 1},
                           'upkeep': {'workers': 2,
                                      'power': 1},
                           'frequency': 5*ONE_SEC},
             'gold mine': {'image_str': 'images/goldmine.png',
                           'minetime': TEN_SEC,
                           'minegives': {'stone': 20,
                                         'wood': 40,
                                         'iron': 10},
                           'minecosts': {'energy': 20},
                           'confirmdestroy': True,
                           'produces': {'goldore': 1},
                           'upkeep': {'workers': 2,
                                      'power': 1},
                           'frequency': 5*ONE_SEC},
             }

ALL_RECIPES = {
               'stick': {'gives': {'stick': 2},
                         'costs': {'wood': 1,
                                   'energy': 2}},
               'glass': {'gives': {'glass': 1},
                         'costs': {'sand': 2,
                                   'energy': 10}},
               'iron': {'gives': {'iron': 1},
                        'costs': {'ironore': 2,
                                  'energy': 10}},
               'gold': {'gives': {'gold': 1},
                        'costs': {'goldore': 2,
                                  'energy': 10}}
               }

BUILDABLES = {
              'animal trap': {'description': 'Produces 4 food. Consumed on use.',
                              'canbuild': ['g', 'w'],
                              'buildcosts': {'food': 1,
                                             'stone': 1,
                                             'stick': 5,
                                             'energy': 5},
                              'buildtime': TEN_SEC},
              'house': {'description': 'Increases worker capacity. Upkeep: 1 food / 10 sec. ',
                        'canbuild': ['g', 'r', 's', 'i'],
                        'buildcosts': {'stone': 30,
                                       'wood': 40,
                                       'energy': 50},
                        'buildtime': 5*ONE_SEC},
              'farm': {'description': 'Generates 1 food / 10 sec. Needs 1 worker. ',
                       'canbuild': ['g'],
                       'buildcosts': {'stone': 30,
                                      'wood': 40,
                                      'energy': 50},
                       'buildtime': 5*ONE_SEC},
              'fishing shack': {'description': 'Automatically collects nearby fish. Needs 1 worker. ',
                                'canbuild': ['g', 'r', 's', 'i'],
                                'buildcosts': {'stick': 10,
                                               'wood': 20,
                                               'energy': 30},
                                'buildtime': 5*ONE_SEC},
              'forager hut': {'description': 'Automatically collects nearby berries and rocks. Needs 1 worker. ',
                              'canbuild': ['g', 'r', 's', 'i'],
                              'buildcosts': {'stick': 10,
                                             'wood': 20,
                                             'energy': 30},
                              'buildtime': 5*ONE_SEC},
              'lumberjack hut': {'description': 'Automatically chops down trees. Needs 1 worker. ',
                                 'canbuild': ['g', 'r', 's', 'i'],
                                 'buildcosts': {'stone': 30,
                                                'wood': 40,
                                                'energy': 30},
                                 'buildtime': 5 * ONE_SEC},
              'tree farm': {'description': 'Generates 1 wood / 10 sec. Needs 1 worker. ',
                            'canbuild': ['g'],
                            'buildcosts': {'stone': 30,
                                           'wood': 40,
                                           'glass': 40,
                                           'energy': 50},
                            'buildtime': 5*ONE_SEC},
              'prospector': {'description': 'Automatically mines boulders and ores. Needs 1 worker. ',
                             'canbuild': ['g', 'r', 's', 'i'],
                             'buildcosts': {'iron': 10,
                                            'stone': 20,
                                            'wood': 20,
                                            'energy': 30},
                             'buildtime': 5 * ONE_SEC},
              'wood generator': {'description': 'Consumes 1 wood and generates 2 power. ',
                                 'canbuild': ['g', 'r', 's', 'i'],
                                 'buildcosts': {'iron': 10,
                                                'stone': 20,
                                                'wood': 20,
                                                'energy': 30},
                                 'buildtime': 5 * ONE_SEC},
              'iron mine': {'description': 'Generates 1 iron ore / 10 sec. Needs 2 workers and 1 power. ',
                            'canbuild': ['r'],
                            'buildcosts': {'stone': 40,
                                           'wood': 80,
                                           'iron': 20,
                                           'energy': 80},
                            'buildtime': TEN_SEC},
              'gold mine': {'description': 'Generates 1 gold ore / 10 sec. Needs 2 workers and 1 power. ',
                            'canbuild': ['r'],
                            'buildcosts': {'stone': 40,
                                           'wood': 80,
                                           'iron': 20,
                                           'energy': 80},
                            'buildtime': TEN_SEC},
              }

ITEMS = {
         'energy': {'i_cap': 'Energy',
                    'lower': 'energy',
                    'plural': 'energy',
                    'plural_i_cap': 'Energy',
                    'sell_value': 0},
         'coins': {'i_cap': 'Coin',
                   'lower': 'coin',
                   'plural': 'coins',
                   'plural_i_cap': 'Coins',
                   'sell_value': 0},
         'workers': {'i_cap': 'Worker',
                     'lower': 'worker',
                     'plural': 'workers',
                     'plural_i_cap': 'Workers',
                     'sell_value': 0},
         'wood': {'i_cap': 'Wood',
                  'lower': 'wood',
                  'plural': 'pieces of wood',
                  'plural_i_cap': 'Pieces of wood',
                  'sell_value': 2},
         'stick': {'i_cap': 'Stick',
                   'lower': 'stick',
                   'plural': 'sticks',
                   'plural_i_cap': 'Sticks',
                   'sell_value': 1},
         'stone': {'i_cap': 'Stone',
                   'lower': 'stone',
                   'plural': 'stones',
                   'plural_i_cap': 'Stones',
                   'sell_value': 1},
         'food': {'i_cap': 'Food',
                  'lower': 'portion of food',
                  'plural': 'portions of food',
                  'plural_i_cap': 'Portions of food',
                  'sell_value': 2},
         'ironore': {'i_cap': 'Iron ore',
                     'lower': 'iron ore',
                     'plural': 'iron ore',
                     'plural_i_cap': 'Iron ore',
                     'sell_value': 2},
         'iron': {'i_cap': 'Iron',
                  'lower': 'iron ingot',
                  'plural': 'iron ingots',
                  'plural_i_cap': 'Iron Ingots',
                  'sell_value': 10},
         'goldore': {'i_cap': 'Gold ore',
                     'lower': 'gold ore',
                     'plural': 'gold ore',
                     'plural_i_cap': 'Gold ore',
                     'sell_value': 3},
         'gold': {'i_cap': 'Gold',
                  'lower': 'gold ingot',
                  'plural': 'gold ingots',
                  'plural_i_cap': 'Gold ingots',
                  'sell_value': 20},
         'sand': {'i_cap': 'Sand',
                  'lower': 'pile of sand',
                  'plural': 'piles of sand',
                  'plural_i_cap': 'Piles of sand',
                  'sell_value': 1},
         'glass': {'i_cap': 'Glass',
                   'lower': 'pane of glass',
                   'plural': 'panes of glass',
                   'plural_i_cap': 'Panes of glass',
                   'sell_value': 5},
         'gem': {'i_cap': 'Gem',
                 'lower': 'gem',
                 'plural': 'gems',
                 'plural_i_cap': 'Gems',
                 'sell_value': 100},
         'fish': {'i_cap': 'Fish',
                  'lower': 'fish',
                  'plural': 'fishing spots',
                  'plural_i_cap': 'Fishing spots'},
         'rock': {'i_cap': 'Rock',
                  'lower': 'rock',
                  'plural': 'rocks',
                  'plural_i_cap': 'Rocks'},
         'boulder': {'i_cap': 'Boulder',
                     'lower': 'boulder',
                     'plural': 'boulders',
                     'plural_i_cap': 'Boulders'},
         'irondeposit': {'i_cap': 'Iron deposit',
                         'lower': 'iron deposit',
                         'plural': 'iron deposits',
                         'plural_i_cap': 'iron deposits'},
         'golddeposit': {'i_cap': 'Gold deposit',
                         'lower': 'gold deposit',
                         'plural': 'gold deposits',
                         'plural_i_cap': 'Gold deposits'},
         'tree': {'i_cap': 'Tree',
                  'lower': 'tree',
                  'plural': 'trees',
                  'plural_i_cap': 'Trees'},
         'bush': {'i_cap': 'Bush',
                  'lower': 'bush',
                  'plural': 'bushes',
                  'plural_i_cap': 'Bushes'},
         'treasure': {'i_cap': 'Treasure',
                      'lower': 'treasure',
                      'plural': 'treasure chests',
                      'plural_i_cap': 'Treasure chests'},
         'loosegem': {'i_cap': 'Gem',
                      'lower': 'gem',
                      'plural': 'gems',
                      'plural_i_cap': 'Gems'},
         'house': {'i_cap': 'House',
                   'lower': 'house',
                   'plural': 'houses',
                   'plural_i_cap': 'Houses'},
         'farm': {'i_cap': 'Farm',
                  'lower': 'farm',
                  'plural': 'farms',
                  'plural_i_cap': 'Farms'},
         'fishing shack': {'i_cap': 'Fishing shack',
                           'lower': 'fishing shack',
                           'plural': 'fishing shacks',
                           'plural_i_cap': 'Fishing shacks'},
         'animal trap': {'i_cap': 'Animal Trap',
                         'lower': 'animal trap',
                         'plural': 'animal traps',
                         'plural_i_cap': 'Animal traps'},
         'forager hut': {'i_cap': 'Forager hut',
                         'lower': 'forager hut',
                         'plural': 'forager huts',
                         'plural_i_cap': 'Forager huts'},
         'lumberjack hut': {'i_cap': 'Lumberjack hut',
                            'lower': 'lumberjack hut',
                            'plural': 'lumberjack huts',
                            'plural_i_cap': 'Lumberjack huts'},
         'tree farm': {'i_cap': 'Tree farm',
                       'lower': 'tree farm',
                       'plural': 'tree farms',
                       'plural_i_cap': 'Tree farms'},
         'prospector': {'i_cap': 'Prospector',
                        'lower': 'prospector',
                        'plural': 'prospectors',
                        'plural_i_cap': 'Prospectors'},
         'wood generator': {'i_cap': 'Wood generator',
                            'lower': 'wood generator',
                            'plural': 'wood generators',
                            'plural_i_cap': 'Wood generators'},
         'iron mine': {'i_cap': 'Iron mine',
                       'lower': 'iron mine',
                       'plural': 'iron mines',
                       'plural_i_cap': 'Iron mines'},
         'gold mine': {'i_cap': 'Gold mine',
                       'lower': 'gold mine',
                       'plural': 'gold mines',
                       'plural_i_cap': 'Gold mines'},
         }

PERKS = {
         '000': {'name': 'Bonus Stone',
                 'cost': 50,
                 'description': 'Get 50% more stone from boulders (additive).',
                 'dependencies': None,
                 'bonuses': {'minegives': {'boulder': {'stone': 0.5}}}},
         '001': {'name': 'Bonuser Stone',
                 'cost': 100,
                 'description': 'Get 100% more stone from rocks and boulders (additive).',
                 'dependencies': ['000'],
                 'bonuses': {'minegives': {'rock': {'stone': 1.0},
                                           'boulder': {'stone': 1.0}}}},
         '002': {'name': 'Outsourcing',
                 'cost': 200,
                 'description': 'Crafting no longer costs Energy.',
                 'dependencies': ['011'],
                 'bonuses': {'free crafting': True}},
         '003': {'name': 'More Outsourcing',
                 'cost': 200,
                 'description': 'Building no longer costs Energy.',
                 'dependencies': ['011'],
                 'bonuses': {'free building': True}},
         '011': {'name': 'Melting',
                 'cost': 50,
                 'description': 'Learn how to make glass and how to smelt iron and gold.',
                 'dependencies': ['000'],
                 'knowledge': {'recipes': ['glass', 'iron', 'gold']}},
         '012': {'name': 'Prospecting',
                 'cost': 50,
                 'description': 'Learn how to install prospectors who can mine Boulders and ore.',
                 'dependencies': ['011', '102'],
                 'knowledge': {'buildings': ['prospector']}},
         '013': {'name': 'Better mining',
                 'cost': 100,
                 'description': 'Get 50% more stone from boulders and ore when mining (additive).',
                 'dependencies': ['012'],
                 'bonuses': {'minegives': {'boulder': {'stone': 0.5},
                                           'irondeposit': {'ironore': 0.5},
                                           'golddeposit': {'goldore': 0.5}}}},
         '021': {'name': 'Power!',
                 'cost': 100,
                 'description': 'Learn how to build a generator that burns wood to create power. ',
                 'dependencies': ['011'],
                 'knowledge': {'buildings': ['wood generator']}},
         '100': {'name': 'Bonus Wood',
                 'cost': 50,
                 'description': 'Get 50% more wood from trees (additive).',
                 'dependencies': ['000'],
                 'bonuses': {'minegives': {'tree': {'wood': 0.5}}}},
         '102': {'name': 'People!',
                 'cost': 50,
                 'description': 'Learn how to build houses. ',
                 'dependencies': ['100'],
                 'knowledge': {'buildings': ['house']}},
         '103': {'name': 'Market!',
                 'cost': 50,
                 'description': 'Unlock the Buying tab. ',
                 'dependencies': ['102'],
                 'bonuses': {'buying': True}},
         '113': {'name': 'Forager Hut',
                 'cost': 50,
                 'description': 'Learn how to build forager huts.',
                 'dependencies': ['102'],
                 'knowledge': {'buildings': ['forager hut']}},
         '114': {'name': 'Lumberjack Hut',
                 'cost': 50,
                 'description': 'Learn how to build lumberjack huts.',
                 'dependencies': ['102'],
                 'knowledge': {'buildings': ['lumberjack hut']}},
         '115': {'name': 'Fishing Shack',
                 'cost': 50,
                 'description': 'Learn how to build fishing shacks.',
                 'dependencies': ['102'],
                 'knowledge': {'buildings': ['fishing shack']}},
         '123': {'name': 'Farm',
                 'cost': 100,
                 'description': 'Learn how to build farms.',
                 'dependencies': ['113'],
                 'knowledge': {'buildings': ['farm']}},
         '124': {'name': 'Tree Farm',
                 'cost': 100,
                 'description': 'Learn how to build tree farms.',
                 'dependencies': ['114'],
                 'knowledge': {'buildings': ['tree farm']}},
         '131': {'name': 'Bonuser Wood',
                 'cost': 100,
                 'description': 'Get 50% more wood from trees (additive).',
                 'dependencies': ['100'],
                 'bonuses': {'minegives': {'tree': {'wood': 0.5}}}},
         '141': {'name': 'Faster Wood',
                 'cost': 50,
                 'description': 'Chop trees 50% faster (multiplicative).',
                 'dependencies': ['100'],
                 'bonuses': {'minetime': {'tree': 0.5}}},
         '142': {'name': 'Fasterer Wood',
                 'cost': 100,
                 'description': 'Chop trees 50% faster (multiplicative).',
                 'dependencies': ['141'],
                 'bonuses': {'minetime': {'tree': 0.5}}},
         '200': {'name': 'Bonus Ore',
                 'cost': 100,
                 'description': 'Get 50% more ore from deposits (additive).',
                 'dependencies': ['100'],
                 'bonuses': {'minegives': {'golddeposit': {'goldore': 0.5},
                                           'irondeposit': {'ironore': 0.5}}}},
         '201': {'name': 'Bonuser Ore',
                 'cost': 200,
                 'description': 'Get 100% more ore from deposits (additive).',
                 'dependencies': ['200'],
                 'bonuses': {'minegives': {'golddeposit': {'goldore': 1.0},
                                           'irondeposit': {'ironore': 1.0}}}},
         '211': {'name': 'Iron Mine',
                 'cost': 100,
                 'description': 'Learn how to build iron mines.',
                 'dependencies': ['200', '021', '102'],
                 'knowledge': {'buildings': ['iron mine']}},
         '212': {'name': 'Gold Mine',
                 'cost': 200,
                 'description': 'Learn how to build gold mines.',
                 'dependencies': ['211', '021', '102'],
                 'knowledge': {'buildings': ['gold mine']}},
         }

INVENTORY_EXCLUDE = ['energy', 'coins']
BUY_EXCLUDE = ['energy', 'coins', 'ironore', 'goldore', 'gold', 'gem']

GAME_AREA_RECT = (GAME_OFFSETS['x'], GAME_OFFSETS['y'], GAME_WIDTH, GAME_HEIGHT)
MAP_OFFSET = ((GAME_WIDTH - (MAP_SIZE*TILE_WIDTH)) / 2,
              (GAME_HEIGHT - (MAP_SIZE*TILE_HEIGHT)) / 2)

PERK_RECT = (700, 75, 450, 450)


FONTS = {'small': pygame.font.SysFont(None, 15),
         'medium': pygame.font.SysFont(None, 25),
         '20': pygame.font.SysFont(None, 20),
         'mediumbold': pygame.font.SysFont(None, 25, True),
         '45': pygame.font.SysFont(None, 45),
         'large': pygame.font.SysFont(None, 50)}
